from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]

REQUIRED_PROMPT03_FILES = [
    "PROMPT03_CONTINUITY_AUDIT.md",
    "COMMERCIAL_TARGET_STATE.md",
    "PROMPT03_MASTER_PLAN.md",
    "PROMPT03_PHASE_TRACKER.md",
    "task_rubric.md",
    "STATUS.md",
    "DECISIONS.md",
    "REJECTED_IDEAS.md",
    "research/source_refresh_log.md",
    "research/source_freshness_matrix.md",
    "research/source_reliability_matrix.md",
    "research/source_coverage_b2c.md",
    "research/source_coverage_b2b.md",
    "research/source_coverage_commercial.md",
    "research/source_gap_matrix.md",
    "model/commercial_question_set.md",
    "model/colombo_boundary_v1.md",
    "model/colombo_zone_map.md",
    "model/b2c_ontology_v1.md",
    "model/b2b_ontology_v1.md",
    "model/pain_domain_ontology.md",
    "model/adoption_friction_ontology.md",
    "model/affordability_ontology.md",
    "model/explainability_ontology.md",
    "population/b2c_household_archetypes_v2.py",
    "population/b2c_person_archetypes_v2.py",
    "population/b2c_language_model.py",
    "population/b2c_trust_model.py",
    "population/b2c_digital_readiness.py",
    "population/b2c_device_connectivity.py",
    "population/b2c_payment_readiness.py",
    "population/b2c_mobility_model.py",
    "population/b2c_budget_model.py",
    "population/b2c_lifestage_triggers.py",
    "population/b2c_need_intensity.py",
    "population/b2c_urgency.py",
    "population/b2c_problem_frequency.py",
    "population/b2c_channel_reachability.py",
    "population/b2c_conversion_friction.py",
    "population/b2c_retention_model.py",
    "population/b2c_referral_model.py",
    "population/b2c_substitutes.py",
    "firms/b2b_sector_taxonomy_v2.py",
    "firms/b2b_size_classes.py",
    "firms/b2b_informality_model.py",
    "firms/b2b_digital_maturity.py",
    "firms/b2b_workflow_complexity.py",
    "firms/b2b_owner_sophistication.py",
    "firms/b2b_customer_interaction.py",
    "firms/b2b_admin_burden.py",
    "firms/b2b_data_readiness.py",
    "firms/b2b_staff_intensity.py",
    "firms/b2b_payment_cycle_friction.py",
    "firms/b2b_procurement_speed.py",
    "firms/b2b_ability_to_pay.py",
    "firms/b2b_roi_tolerance.py",
    "firms/b2b_sales_cycle.py",
    "firms/b2b_channel_reachability.py",
    "firms/b2b_substitute_pressure.py",
    "firms/b2b_expansion_potential.py",
    "offers/offer_schema_v2.json",
    "offers/offer_normalizer_v2.py",
    "offers/offer_quality_scoring.py",
    "scoring/b2c_fit_v2.py",
    "scoring/b2b_fit_v2.py",
    "scoring/market_entry_difficulty.py",
    "scoring/channel_acquisition_difficulty.py",
    "scoring/pricing_fit.py",
    "scoring/retention_expansion_value.py",
    "scoring/commercial_attractiveness.py",
    "experiments/scenario_pack_v2.py",
    "experiments/run_rankings_v2.py",
    "validation/red_team_audit.py",
    "validation/sensitivity_v2.py",
    "outputs/b2c_population_v2.csv",
    "outputs/b2b_population_v2.csv",
    "outputs/top_opportunities.csv",
    "outputs/top_segments.csv",
    "outputs/opportunity_explainers.json",
    "outputs/scenario_comparison.csv",
    "outputs/offer_competitor_graph.json",
    "outputs/offer_domain_clusters.json",
    "reports/b2c_model_v2_report.md",
    "reports/b2b_model_v2_report.md",
    "reports/offer_ontology_v2.md",
    "reports/offer_corpus_v2_report.md",
    "reports/scoring_v2_report.md",
    "reports/commercial_value_brief.md",
    "reports/model_card_v1.md",
    "reports/segment_playbooks.md",
    "reports/validation_report.md",
    "qa/test_report.md",
    "qa/known_gaps.md",
    "qa/morning_decisions.md",
    "qa/red_team_findings.md",
    "qa/repair_log.md",
    "qa/known_limits_v2.md",
    "HANDOFF/PROMPT03_EXECUTIVE_BRIEF.md",
    "HANDOFF/PROMPT03_BUILD_STATUS.md",
    "HANDOFF/PROMPT03_TOP_FINDINGS.md",
    "HANDOFF/PROMPT03_NEXT_72_HOURS.md",
    "HANDOFF/PROMPT03_NEXT_2_WEEKS.md",
    "evidence/prompt03_manifest.json",
    "evidence/source_catalog.json",
    "evidence/hash_log.csv",
    "evidence/run_log.md",
    "scripts/run_prompt03_pipeline.py",
    "scripts/package_prompt03_evidence.py",
]


def test_prompt03_artifacts_exist_and_are_non_empty() -> None:
    missing = []
    empty = []

    for relative_path in REQUIRED_PROMPT03_FILES:
        path = REPO_ROOT / relative_path
        if not path.exists():
            missing.append(relative_path)
        elif path.is_file() and not path.read_text(encoding="utf-8").strip():
            empty.append(relative_path)

    assert not missing, f"Missing Prompt #03 artifacts: {missing}"
    assert not empty, f"Empty Prompt #03 artifacts: {empty}"
