"""Support constants for the Prompt #03 commercial-grade market simulator sprint."""

from __future__ import annotations


SOURCE_REGISTRY = [
    {
        "source_id": "dcs-cph-2024-main-page",
        "title": "DCS Census of Population and Housing 2024 main page",
        "url": "https://www.statistics.gov.lk/Census/PopulationAndHousing2024",
        "relative_path": "data/snapshots/sources/dcs/cph2024_main.html",
        "download_mode": "text",
        "source_type": "official",
        "reliability_score": 5,
        "freshness_note": "2024 census publication page used on 2026-03-17",
        "usage": "main Colombo population and housing source hub",
        "claim_type": "FACT",
        "usable_now": True,
    },
    {
        "source_id": "dcs-cph-2024-population-prelim",
        "title": "DCS CPH 2024 Population Preliminary Report",
        "url": "https://www.statistics.gov.lk/Resource/en/Population/CPH_2024/Population_Preliminary_Report.pdf",
        "relative_path": "data/snapshots/sources/dcs/cph2024_population_preliminary_report.pdf",
        "download_mode": "binary",
        "source_type": "official",
        "reliability_score": 5,
        "freshness_note": "2024 preliminary population report",
        "usage": "district population and density anchors",
        "claim_type": "FACT",
        "usable_now": True,
    },
    {
        "source_id": "dcs-cph-2024-housing-prelim",
        "title": "DCS CPH 2024 Housing Preliminary Report",
        "url": "https://www.statistics.gov.lk/Resource/en/Population/CPH_2024/Housing_Preliminary_Report.pdf",
        "relative_path": "data/snapshots/sources/dcs/cph2024_housing_preliminary_report.pdf",
        "download_mode": "binary",
        "source_type": "official",
        "reliability_score": 5,
        "freshness_note": "2024 preliminary housing report",
        "usage": "district housing and household anchors",
        "claim_type": "FACT",
        "usable_now": True,
    },
    {
        "source_id": "dcs-cph-2024-basic-population-ds",
        "title": "DCS CPH 2024 Basic Population Information by District and DS Division",
        "url": "https://www.statistics.gov.lk/Resource/en/Population/CPH_2024/Report_Basic_Information_ByDistricts_and_DsDivisions.pdf",
        "relative_path": "data/snapshots/sources/dcs/cph2024_basic_population_district_ds.pdf",
        "download_mode": "binary",
        "source_type": "official",
        "reliability_score": 5,
        "freshness_note": "2024 DS-level population table",
        "usage": "Colombo zone weights and DS-level population anchors",
        "claim_type": "FACT",
        "usable_now": True,
    },
    {
        "source_id": "dcs-cph-2024-gn-population",
        "title": "DCS CPH 2024 Basic Population Information by GN Division",
        "url": "https://www.statistics.gov.lk/Resource/en/Population/CPH_2024/GN_population_pdf.pdf",
        "relative_path": "data/snapshots/sources/dcs/cph2024_gn_population.pdf",
        "download_mode": "binary",
        "source_type": "official",
        "reliability_score": 4,
        "freshness_note": "2024 GN-level population table",
        "usage": "future neighborhood-level zone refinement",
        "claim_type": "FACT",
        "usable_now": False,
    },
    {
        "source_id": "dcs-cph-2024-gn-housing",
        "title": "DCS CPH 2024 Basic Housing Information by GN Division",
        "url": "https://www.statistics.gov.lk/Resource/en/Population/CPH_2024/GN_housing_pdf.pdf",
        "relative_path": "data/snapshots/sources/dcs/cph2024_gn_housing.pdf",
        "download_mode": "binary",
        "source_type": "official",
        "reliability_score": 4,
        "freshness_note": "2024 GN-level housing table",
        "usage": "future housing-density and neighborhood refinement",
        "claim_type": "FACT",
        "usable_now": False,
    },
    {
        "source_id": "dcs-hies-2019-nada",
        "title": "DCS HIES 2019 NADA study page",
        "url": "https://nada.statistics.gov.lk/index.php/catalog/study/LKA-DCS-HIES-2019-V01",
        "relative_path": "data/snapshots/sources/dcs/hies_2019_nada.html",
        "download_mode": "text",
        "source_type": "official",
        "reliability_score": 5,
        "freshness_note": "2019 household microdata catalog page",
        "usage": "household income expenditure and composition source registry",
        "claim_type": "FACT",
        "usable_now": True,
    },
    {
        "source_id": "dcs-economic-crisis-households-2023",
        "title": "DCS Household Survey on Impact of Economic Crisis 2023",
        "url": "https://www.statistics.gov.lk/Resource/en/OtherCensusandSurveys/SurveyReports/HHImpact_of_Economic_crisis_2023_Final_Report.pdf",
        "relative_path": "data/snapshots/sources/dcs/household_economic_crisis_2023.pdf",
        "download_mode": "binary",
        "source_type": "official",
        "reliability_score": 5,
        "freshness_note": "2023 household stress survey",
        "usage": "budget tightness and affordability logic",
        "claim_type": "FACT",
        "usable_now": True,
    },
    {
        "source_id": "dcs-computer-literacy-2025-h1",
        "title": "DCS Computer Literacy Statistics 2025 First Six Months",
        "url": "https://www.statistics.gov.lk/Resource/en/ComputerLiteracy/Bulletins/2025-FirstSixMonths.pdf",
        "relative_path": "data/snapshots/sources/dcs/computer_literacy_2025_h1.pdf",
        "download_mode": "binary",
        "source_type": "official",
        "reliability_score": 5,
        "freshness_note": "2025 H1 digital-readiness bulletin",
        "usage": "consumer digital readiness and education-linked access proxies",
        "claim_type": "FACT",
        "usable_now": True,
    },
    {
        "source_id": "dcs-lfs-q2-2025",
        "title": "DCS Labour Force Survey Quarterly Report 2025 Q2",
        "url": "https://www.statistics.gov.lk/Resource/en/LabourForce/Quarterly_Reports/2025Q2report.pdf",
        "relative_path": "data/snapshots/sources/dcs/lfs_q2_2025.pdf",
        "download_mode": "binary",
        "source_type": "official",
        "reliability_score": 5,
        "freshness_note": "2025 Q2 labour-market bulletin",
        "usage": "employment pressure and youth urgency logic",
        "claim_type": "FACT",
        "usable_now": True,
    },
    {
        "source_id": "dcs-informal-non-agri",
        "title": "DCS Informal Non-Agricultural Activities Final Report",
        "url": "https://www.statistics.gov.lk/Economic/FinalReport_Informal_NonAgri.pdf",
        "relative_path": "data/snapshots/sources/dcs/informal_non_agri_final_report.pdf",
        "download_mode": "binary",
        "source_type": "official",
        "reliability_score": 4,
        "freshness_note": "official but older than 2024 census anchors",
        "usage": "firm informality and non-agricultural business structure",
        "claim_type": "FACT",
        "usable_now": True,
    },
    {
        "source_id": "cbsl-annual-report-2024-page",
        "title": "CBSL annual reports index page",
        "url": "https://www.cbsl.gov.lk/en/publications/economic-and-financial-reports/annual-reports",
        "relative_path": "data/snapshots/sources/cbsl/annual_report_2024.html",
        "download_mode": "text",
        "source_type": "official",
        "reliability_score": 5,
        "freshness_note": "annual-reports index visible on 2026-03-17",
        "usage": "macro-commercial context and annual report discovery",
        "claim_type": "FACT",
        "usable_now": True,
    },
    {
        "source_id": "cbsl-payments-bulletin-page",
        "title": "CBSL home page used as payments-source fallback",
        "url": "https://www.cbsl.gov.lk/en",
        "relative_path": "data/snapshots/sources/cbsl/payments_bulletin.html",
        "download_mode": "text",
        "source_type": "official",
        "reliability_score": 3,
        "freshness_note": "CBSL home page fallback visible on 2026-03-17",
        "usage": "official payments evidence fallback while bulletin URL remains unstable",
        "claim_type": "FACT",
        "usable_now": True,
    },
    {
        "source_id": "trcsl-telecom-statistics-page",
        "title": "TRCSL home page used for telecom-statistics fallback",
        "url": "https://www.trc.gov.lk/",
        "relative_path": "data/snapshots/sources/trcsl/telecommunication_statistics.html",
        "download_mode": "text",
        "source_type": "official",
        "reliability_score": 3,
        "freshness_note": "TRCSL home page fallback visible on 2026-03-17",
        "usage": "official telecom evidence fallback while statistics URL remains unstable",
        "claim_type": "FACT",
        "usable_now": True,
    },
    {
        "source_id": "sl-dpa-home",
        "title": "Sri Lanka Data Protection Authority",
        "url": "https://www.dpa.gov.lk/",
        "relative_path": "data/snapshots/sources/dpa/home.html",
        "download_mode": "text",
        "source_type": "official",
        "reliability_score": 4,
        "freshness_note": "official DPA site visible on 2026-03-17",
        "usage": "commercial compliance and trust doctrine",
        "claim_type": "FACT",
        "usable_now": True,
    },
    {
        "source_id": "sl-dpa-act-page",
        "title": "Sri Lanka Data Protection Authority home used for act fallback",
        "url": "https://www.dpa.gov.lk/",
        "relative_path": "data/snapshots/sources/dpa/data_protection_act.html",
        "download_mode": "text",
        "source_type": "official",
        "reliability_score": 3,
        "freshness_note": "official DPA home fallback visible on 2026-03-17",
        "usage": "regulatory sensitivity scoring and compliance fallback",
        "claim_type": "FACT",
        "usable_now": True,
    },
]


CHOSEN_WEAPONS = [
    {
        "area": "weapon discovery",
        "weapon": "find-skills",
        "why": "User explicitly invoked it and required expanded multi-drive discovery.",
        "material_help": True,
    },
    {
        "area": "D-drive search",
        "weapon": "d-drive-weapon-search",
        "why": "Used as the closest local TAC search doctrine for cross-drive weapon discovery.",
        "material_help": True,
    },
    {
        "area": "skill routing",
        "weapon": "using-superpowers",
        "why": "Required by the repo instructions to avoid generic reasoning before skill selection.",
        "material_help": True,
    },
    {
        "area": "design discipline",
        "weapon": "brainstorming",
        "why": "Used to frame the commercial-grade v1 boundary before code spread.",
        "material_help": True,
    },
    {
        "area": "plan execution",
        "weapon": "writing-plans",
        "why": "Prompt #03 spans many interlocked modeling and evidence phases.",
        "material_help": True,
    },
    {
        "area": "implementation discipline",
        "weapon": "test-driven-development",
        "why": "New Prompt #03 modules were driven behind failing tests first.",
        "material_help": True,
    },
    {
        "area": "repair loop",
        "weapon": "systematic-debugging",
        "why": "Needed whenever the expanding pipeline or data contracts fail.",
        "material_help": True,
    },
    {
        "area": "completion gate",
        "weapon": "verification-before-completion",
        "why": "Prevents fake commercial-ready claims before tests and artifact generation pass.",
        "material_help": True,
    },
]


WEAPON_GAPS = [
    "No exposed CPD browser tool exists in this session even though the prompt requires CPD for browser work. Source work therefore uses direct HTTP snapshots and the built-in web tool instead of a CPD session.",
    "No dedicated local weapon exists for Sri Lanka synthetic market calibration, so calibration logic remains source-backed manual modeling rather than domain-specific automation.",
    "No dedicated local weapon exists for vendor-pricing extraction across opaque AI product pages, so pricing bands remain explicit INFERENCE where vendor pages hide price.",
]


PHASE_TITLES = {
    1: "Re-read Prompt #01 and Prompt #02 outputs",
    2: "Build a repo reality map",
    3: "Search D drive for skills and weapons",
    4: "Search Downloads for extra skills and weapons",
    5: "Freeze CPD/browser usage doctrine",
    6: "Create the 7-day master execution plan",
    7: "Create the 100-phase tracker",
    8: "Freeze naming paths and evidence rules",
    9: "Create the commercial target-state definition",
    10: "Write the anti-fake-realism doctrine",
    11: "Refresh the source hierarchy",
    12: "Download and snapshot critical official sources",
    13: "Hash and catalog source artifacts",
    14: "Build a source freshness matrix",
    15: "Build a source reliability matrix",
    16: "Build B2C source coverage",
    17: "Build B2B source coverage",
    18: "Build pricing and adoption source coverage",
    19: "Build a source gap matrix",
    20: "Split usable now versus infer later versus impossible now",
    21: "Freeze the commercial question set",
    22: "Freeze the Colombo core boundary",
    23: "Define Colombo sub-zones",
    24: "Define commuter-belt relations without scope creep",
    25: "Freeze the B2C ontology",
    26: "Freeze the B2B ontology",
    27: "Freeze the pain-domain ontology",
    28: "Freeze the adoption-friction ontology",
    29: "Freeze the affordability ontology",
    30: "Freeze the explainability ontology",
    31: "Rebuild the B2C household archetype system",
    32: "Rebuild the B2C person archetype system",
    33: "Add language-preference modeling",
    34: "Add trust and skepticism modeling",
    35: "Add digital readiness modeling",
    36: "Add device and connectivity modeling",
    37: "Add payment readiness modeling",
    38: "Add commute and mobility burden modeling",
    39: "Add budget tightness and discretionary-spend modeling",
    40: "Add life-stage trigger modeling",
    41: "Add B2C need-intensity modeling",
    42: "Add B2C urgency modeling",
    43: "Add B2C frequency-of-problem modeling",
    44: "Add B2C channel-reachability modeling",
    45: "Add B2C conversion-friction modeling",
    46: "Add B2C retention-likelihood modeling",
    47: "Add B2C referral and virality potential modeling",
    48: "Add B2C local substitute availability modeling",
    49: "Generate the B2C synthetic population v2",
    50: "Run B2C validation sanity and stability checks",
    51: "Rebuild the B2B sector taxonomy",
    52: "Split B2B into size classes",
    53: "Add informality and semi-formality modeling",
    54: "Add firm digital maturity modeling",
    55: "Add workflow complexity modeling",
    56: "Add owner and manager sophistication modeling",
    57: "Add customer-interaction intensity modeling",
    58: "Add admin and compliance burden modeling",
    59: "Add data readiness modeling",
    60: "Add staff intensity and labor pain modeling",
    61: "Add payment-cycle friction modeling",
    62: "Add procurement-speed modeling",
    63: "Add ability-to-pay modeling",
    64: "Add buyer ROI-tolerance modeling",
    65: "Add sales-cycle length modeling",
    66: "Add B2B channel-reachability modeling",
    67: "Add local incumbent and substitute pressure modeling",
    68: "Add within-account expansion potential modeling",
    69: "Generate the B2B synthetic population v2",
    70: "Run B2B validation sanity and stability checks",
    71: "Rebuild the offer ontology",
    72: "Add pricing-normalization fields",
    73: "Add implementation-friction fields",
    74: "Add onboarding-burden fields",
    75: "Add language-support fields",
    76: "Add trust-barrier fields",
    77: "Add compliance and data-sensitivity fields",
    78: "Add ROI-path fields",
    79: "Add evidence-strength fields",
    80: "Add support and vendor-durability fields",
    81: "Expand the India-first AI offer corpus",
    82: "Build a Colombo local-alternatives corpus",
    83: "Build a Sri Lanka alternatives corpus",
    84: "Build an international benchmark corpus",
    85: "Normalize all offer records into one schema",
    86: "Deduplicate and merge overlapping offers",
    87: "Score source quality for each offer",
    88: "Build the substitute and competitor graph",
    89: "Build domain clusters across all offers",
    90: "Run offer-corpus QA and schema validation",
    91: "Rebuild the B2C fit engine",
    92: "Rebuild the B2B fit engine",
    93: "Build the market-entry difficulty engine",
    94: "Build the channel-acquisition difficulty engine",
    95: "Build the pricing-fit and affordability engine",
    96: "Build the retention and expansion value engine",
    97: "Build the combined commercial-attractiveness engine",
    98: "Build scenario packs for multiple conditions",
    99: "Build sensitivity uncertainty and red-team layers",
    100: "Produce the final commercial handoff and evidence pack",
}
